DROP DATABASE IF EXISTS WORKABLE;
CREATE DATABASE WORKABLE;
USE WORKABLE;

CREATE TABLE ROL (
	ROL_ID TINYINT PRIMARY KEY,
    ROL_NOMB VARCHAR(10) UNIQUE
);

CREATE TABLE TIPO_DOCUMENTO (
	TIP_DOC_ID TINYINT PRIMARY KEY,
    DOC_NOMB VARCHAR(20) UNIQUE
);

CREATE TABLE DEPARTAMENTO (
	DEPAR_ID INT PRIMARY KEY,
    DEPAR_NOMB VARCHAR (50) UNIQUE
);

CREATE TABLE CIUDAD (
	CIUD_ID INT PRIMARY KEY,
    CIDUD_NOMB VARCHAR(50) UNIQUE,
    DEPAR_ID INT NOT NULL,
    CONSTRAINT FK_DEPAR_ID FOREIGN KEY (DEPAR_ID) REFERENCES DEPARTAMENTO(DEPAR_ID)
);

CREATE TABLE CATEGORIA_EMPR (
	CATEG_ID INT PRIMARY KEY,
    NOMB_CATEG VARCHAR(100) UNIQUE,
    DESCRIPCION VARCHAR(255) UNIQUE
);

CREATE TABLE EMPRESA (
	EMPR_ID INTEGER PRIMARY KEY,
    NOMB_EMPR VARCHAR(100) UNIQUE,
    UBICACION_EMPR VARCHAR(255),
    DESCRIPCION_EMPR TEXT,
    CATEG_ID INT NOT NULL,
    CONSTRAINT FK_CATEG_ID FOREIGN KEY (CATEG_ID) REFERENCES CATEGORIA_EMPR(CATEG_ID)
);

CREATE TABLE VALORACIONES (
	VALR_ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255),
    PUNTUACION TINYINT(1)
);

CREATE TABLE EMPRESA_VALORACIONES (
	EMPR_ID INT,
    VALR_ID INT,
    PRIMARY KEY (EMPR_ID, VALR_ID),
    CONSTRAINT FK_V_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID),
    CONSTRAINT FK_VALR_ID FOREIGN KEY (VALR_ID) REFERENCES VALORACIONES(VARL_ID)
);

CREATE TABLE USUARIO (
	USR_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    CLAVE VARCHAR(255),
    CORREO VARCHAR(255) UNIQUE,
    USR_NAME VARCHAR(255) UNIQUE,
    CIUD_ID INT NOT NULL,
    EMPR_ID INT NOT NULL,
    TIP_DOC_ID TINYINT NOT NULL,
    ROL_ID TINYINT NOT NULL,
    CONSTRAINT fk_CIUD_ID FOREIGN KEY (CIUD_ID) REFERENCES CIUDAD(CIUD_ID),
    CONSTRAINT fk_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID),
    CONSTRAINT fk_TIP_DOC_ID FOREIGN KEY (TIP_DOC_ID) REFERENCES TIPO_DOCUMENTO(TIP_DOC_ID),
    CONSTRAINT fk_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
);

CREATE TABLE DISCAPACIDAD (
	DISCAP_ID TINYINT PRIMARY KEY,
    NOMB_DISCAPACIDAD VARCHAR(50) UNIQUE
);

CREATE TABLE USUARIO_DISCAP (
	USR_ID INT NOT NULL,
    DISCAP_ID TINYINT NOT NULL,
    PRIMARY KEY (USR_ID, DISCAP_ID),
    CONSTRAINT fk_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT fk_DISCAP_ID FOREIGN KEY (DISCAP_ID) REFERENCES DISCAPACIDAD(DISCAP_ID)
);

CREATE TABLE GENERO (
	GENR_ID INT PRIMARY KEY,
    TIP_GENR BIT
);

CREATE TABLE INFO_PERSONAL (
	PERS_ID INT PRIMARY KEY,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO INT UNIQUE NOT NULL,
    FECHA_NACIM DATE,
    FOTO_PERFIL BLOB,
    GENR_ID INT,
    USR_ID INT,
    CONSTRAINT FK_GENR_ID FOREIGN KEY (GENR_ID) REFERENCES GENERO(GENR_ID),
    CONSTRAINT FK_P_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE NIVEL_EDUCATIVO (
	N_EDU_ID INT,
    NOMB_NIV_EDU VARCHAR(255) UNIQUE
);

CREATE TABLE INSTITUCION (
	INSTITU_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    CIUDAD VARCHAR(255),
    DEPARTAMENTO VARCHAR(100),
    PAIS VARCHAR(100)
);

CREATE TABLE INFO_ESTUDIOS (
	ESTUD_ID INT PRIMARY KEY,
    NOMB_ESTUDIO VARCHAR(255),
    FECHA_INI DATE,
    FECHA_FIN DATE,
    CERTIFICACION BLOB,
    N_EDU_ID INT NOT NULL,
    INSTITU_ID INT NOT NULL,
    USR_ID INT NOT NULL,
    CONSTRAINT FK_N_EDU_ID FOREIGN KEY (N_EDU_ID) REFERENCES NIVEL_EDUCATIVO(N_EDU_ID),
    CONSTRAINT FK_INSTITU_ID FOREIGN KEY (INSTITU_ID) REFERENCES INSTITUCION(INSTITUCION_ID),
    CONSTRAINT FK_E_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE INFO_EXPERIENCIA (
	EXPE_ID INT PRIMARY KEY,
    CARGO VARCHAR(255),
    NOMB_EMPR VARCHAR(255),
    FECHA_INI DATE,
    FECHA_SAL DATE,
    DESCRIPCION VARCHAR(255),
    CIUDAD VARCHAR(255),
    PAIS VARCHAR(255),
    USR_ID INT NOT NULL,
    CONSTRAINT FK_X_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE TIPO_CONTRATO (
	TIP_CONT_ID INT PRIMARY KEY,
    NOMB_CONT VARCHAR(255)
);

CREATE TABLE MODALIDAD (
	MODAL_ID INT PRIMARY KEY,
    NOMB_MODAL VARCHAR(255)
);

CREATE TABLE OFERTA (
	OFER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMB_OFERTA VARCHAR (100),
    DESCRIPCION VARCHAR (255),
    UBIC_TRABAJO VARCHAR(100),
    FECHA_PUB DATE,
    FECHA_LIMIT DATE,
    MODAL_ID INT NOT NULL,
    TIP_CONT_ID INT NOT NULL,
    EMPR_ID INT NOT NULL,
    CONSTRAINT MODAL_ID
);
