DROP DATABASE IF EXISTS WORKABLE;
CREATE DATABASE WORKABLE;
USE WORKABLE;

CREATE TABLE ROL (
	ROL_ID TINYINT PRIMARY KEY,
    NOMBRE VARCHAR(10) UNIQUE
);

CREATE TABLE DEPARTAMENTO (
	DEPAR_ID INT PRIMARY KEY,
	NOMBRE VARCHAR (50) UNIQUE
);

CREATE TABLE MUNICIPIO (
	MUNIC_ID INT PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE,
    DEPAR_ID INT NOT NULL,
    CONSTRAINT FK_DEPAR_ID FOREIGN KEY (DEPAR_ID) REFERENCES DEPARTAMENTO(DEPAR_ID)
);

CREATE TABLE CATEGORIA_EMPRE (
	CATEG_ID INT PRIMARY KEY,
	NOMBRE VARCHAR(100) UNIQUE,
	DESCRIPCION VARCHAR(255) UNIQUE
);

CREATE TABLE EMPRESA (#
	EMPRE_ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(100) UNIQUE,
	DESCRIPCION TEXT,
	DIRECCION VARCHAR(100),
    CATEG_ID INT NOT NULL,
    MUNIC_ID INT NOT NULL,
    PUNTUACION_PROMEDIO DECIMAL(3,2) DEFAULT 0.0,
    CONSTRAINT FK_E_CATEG_ID FOREIGN KEY (CATEG_ID) REFERENCES CATEGORIA_EMPRE(CATEG_ID),
    CONSTRAINT FK_E_MUNIC_ID FOREIGN KEY (MUNIC_ID) REFERENCES MUNICIPIO(MUNIC_ID)
);

CREATE TABLE TIPO_DOCUMENTO (
	ID_TIP_DOC INT PRIMARY KEY,
    NOMBRE VARCHAR(255) UNIQUE
);

CREATE TABLE GENERO (
	GENER_ID BIT PRIMARY KEY,
    TIPO VARCHAR(100)
);

CREATE TABLE USUARIO (#
	USR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    CLAVE VARBINARY(255),
    DIRECCION VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) UNIQUE,
    USR_NAME VARCHAR(255) UNIQUE,
    TELEFONO BIGINT UNIQUE NOT NULL,
    FECHA_NACIM DATE,
    FOTO_PERFIL VARCHAR(512),
	GENER_ID BIT,
    MUNIC_ID INT NOT NULL,
    EMPRE_ID INT NULL,
    ROL_ID TINYINT NOT NULL,
    ID_TIP_DOC INT NOT NULL,
    CONSTRAINT FK_PE_GENER_ID FOREIGN KEY (GENER_ID) REFERENCES GENERO(GENER_ID),
    CONSTRAINT FK_MUNIC_ID FOREIGN KEY (MUNIC_ID) REFERENCES MUNICIPIO(MUNIC_ID),
    CONSTRAINT FK_EMPRE_ID FOREIGN KEY (EMPRE_ID) REFERENCES EMPRESA(EMPRE_ID),
    CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID),
    CONSTRAINT FK_ID_TIP_DOC FOREIGN KEY (ID_TIP_DOC) REFERENCES TIPO_DOCUMENTO(ID_TIP_DOC)
);

CREATE TABLE VALORACION (#
	VALR_ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255),
    PUNTUACION DECIMAL(2,1) NOT NULL,
    VALR_FECHA DATE,
    EMPRE_ID INT NOT NULL,
    USR_ID INT NOT NULL,
    CONSTRAINT FK_V_EMPRE_ID FOREIGN KEY (EMPRE_ID) REFERENCES EMPRESA(EMPRE_ID),
    CONSTRAINT FK_V_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT UNICA_VALR UNIQUE (USR_ID, EMPRE_ID) #Para que el usuario no coloque 2 valoraciones en 1 misma empreas
);

CREATE TABLE DISCAPACIDAD (
	DISCAP_ID TINYINT PRIMARY KEY,
    NOMBRE VARCHAR(50) UNIQUE
);

CREATE TABLE USUARIO_DISCAP (#
	USR_ID INT NOT NULL,
    DISCAP_ID TINYINT NOT NULL,
    PRIMARY KEY (USR_ID, DISCAP_ID),
    CONSTRAINT fk_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT fk_DISCAP_ID FOREIGN KEY (DISCAP_ID) REFERENCES DISCAPACIDAD(DISCAP_ID)
);

CREATE TABLE NIVEL_EDUCATIVO (
	NIV_EDU_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(255) UNIQUE
);

CREATE TABLE INSTITUCION (
	INSTI_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) UNIQUE,
    POPULARIDAD INT DEFAULT 0,
    DEPAR_ID INT,
    CONSTRAINT FK_INS_DEPAR_ID FOREIGN KEY (DEPAR_ID) REFERENCES DEPARTAMENTO(DEPAR_ID)
);

CREATE TABLE ESTUDIO (#
    ESTUD_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PROGRAMA VARCHAR(255) NOT NULL,
    FECHA_INI DATE NOT NULL,
    FECHA_FIN DATE NULL,
    CERTIFICADO_URL VARCHAR(512) NULL,
	INSTI_ID INT NOT NULL,
	USR_ID INT NOT NULL,
	NIV_EDU_ID INT NOT NULL,
	CONSTRAINT FK_EST_INSTI_ID FOREIGN KEY (INSTI_ID) REFERENCES INSTITUCION(INSTI_ID),
    CONSTRAINT FK_EST_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT FK_EST_NIV_EDU_ID FOREIGN KEY (NIV_EDU_ID) REFERENCES NIVEL_EDUCATIVO(NIV_EDU_ID)
);

CREATE TABLE EXPERIENCIA (#
	EXPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    CARGO VARCHAR(255),
    NOMB_EMPRE VARCHAR(255),
    FECHA_INI DATE,
    FECHA_FIN DATE,
    DESCRIPCION TEXT,
    CIUDAD VARCHAR(255),
    PAIS VARCHAR(255),
    USR_ID INT NOT NULL,
    CONSTRAINT FK_EXP_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE TIPO_CONTRATO (
	TIP_CONT_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);

CREATE TABLE MODALIDAD (
	MODAL_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);

CREATE TABLE OFERTA (#
	OFER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR (100),
    DESCRIPCION VARCHAR (255),
    DIRECCION VARCHAR(100),
    FECHA_PUBLI DATE,
    FECHA_LIMIT DATE,
    MODAL_ID INT NOT NULL,
    TIP_CONT_ID INT NOT NULL,
    EMPRE_ID INT NOT NULL,
    MUNIC_ID INT NOT NULL,
    CONSTRAINT FK_OFE_MUNIC_ID FOREIGN KEY (MUNIC_ID) REFERENCES MUNICIPIO(MUNIC_ID),
    CONSTRAINT FK_MODAL_ID FOREIGN KEY (MODAL_ID) REFERENCES MODALIDAD(MODAL_ID),
    CONSTRAINT FK_TIP_CONT_ID FOREIGN KEY (TIP_CONT_ID) REFERENCES TIPO_CONTRATO(TIP_CONT_ID),
    CONSTRAINT FK_O_EMPRE_ID FOREIGN KEY (EMPRE_ID) REFERENCES EMPRESA(EMPRE_ID)
);

CREATE TABLE BENEFICIOS (
	BENEF_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(255) UNIQUE
);

CREATE TABLE OFERTA_BENEFICIOS (#
	OFER_ID INT NOT NULL,
    BENEF_ID INT NOT NULL,
    PRIMARY KEY (OFER_ID, BENEF_ID),
    CONSTRAINT FK_BENEF_ID FOREIGN KEY (BENEF_ID) REFERENCES BENEFICIOS(BENEF_ID),
    CONSTRAINT FK_B_OFER_ID FOREIGN KEY (OFER_ID) REFERENCES OFERTA(OFER_ID)
);

CREATE TABLE ESTADO(
	ESTAD_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(10)
);

CREATE TABLE POSTULACIONES (#
	POSTUL_ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_POST DATE,
    ESTAD_ID INT NOT NULL,
    OFER_ID INT NOT NULL,
    USR_ID INT NOT NULL,
	CONSTRAINT FK_ESTAD_ID FOREIGN KEY (ESTAD_ID) REFERENCES ESTADO(ESTAD_ID),
    CONSTRAINT FK_PO_OFER_ID FOREIGN KEY (OFER_ID) REFERENCES OFERTA(OFER_ID),
    CONSTRAINT FK_PO_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);
