DROP DATABASE IF EXISTS WORKABLE;
CREATE DATABASE WORKABLE;
USE WORKABLE;

CREATE TABLE ROL (
	ROL_ID TINYINT PRIMARY KEY,
    NOMB_ROL VARCHAR(10) UNIQUE
);

CREATE TABLE DEPARTAMENTO (
	DEPAR_ID INT PRIMARY KEY,
    NOMB_DEPARTAMENTO VARCHAR (50) UNIQUE
);

CREATE TABLE MUNICIPIO (
	MUNI_ID INT PRIMARY KEY,
    NOMB_MUNICIPIO VARCHAR(50) UNIQUE,
    DEPAR_ID INT NOT NULL,
    CONSTRAINT FK_DEPAR_ID FOREIGN KEY (DEPAR_ID) REFERENCES DEPARTAMENTO(DEPAR_ID)
);

CREATE TABLE CATEGORIA_EMPR (
	CATEG_ID INT PRIMARY KEY,
    NOMB_CATEGORIA VARCHAR(100) UNIQUE,
    DESCRIPCION VARCHAR(255) UNIQUE
);

CREATE TABLE EMPRESA (#
	EMPR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMB_EMPRESA VARCHAR(100) UNIQUE,
    DESCRIPCION_EMPR TEXT,
    DIRECCION_EMPR VARCHAR(100),
    CATEG_ID INT NOT NULL,
    MUNI_ID INT NOT NULL,
    CONSTRAINT FK_E_CATEG_ID FOREIGN KEY (CATEG_ID) REFERENCES CATEGORIA_EMPR(CATEG_ID),
    CONSTRAINT FK_E_MUNI_ID FOREIGN KEY (MUNI_ID) REFERENCES MUNICIPIO(MUNI_ID)
);

CREATE TABLE TIPO_DOCUMENTO (
	ID_TIP_DOC INT PRIMARY KEY,
    NOMB_DOCUMENTO VARCHAR(255) UNIQUE
);

CREATE TABLE GENERO (
	GENR_ID BIT PRIMARY KEY,
    TIP_GENR VARCHAR(100)
);

CREATE TABLE USUARIO (
	USR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    CLAVE VARCHAR(255),
    DIRECCION VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) UNIQUE,
    USR_NAME VARCHAR(255) UNIQUE,
    TELEFONO INT UNIQUE NOT NULL,
    FECHA_NACIM DATE,
    FOTO_PERFIL BLOB,
	GENR_ID BIT,
    MUNI_ID INT NOT NULL,
    EMPR_ID INT NULL,
    ROL_ID TINYINT NOT NULL,
    ID_TIP_DOC INT NOT NULL,
    CONSTRAINT FK_PE_GENR_ID FOREIGN KEY (GENR_ID) REFERENCES GENERO(GENR_ID),
    CONSTRAINT FK_MUNI_ID FOREIGN KEY (MUNI_ID) REFERENCES MUNICIPIO(MUNI_ID),
    CONSTRAINT FK_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID),
    CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID),
    CONSTRAINT FK_ID_TIP_DOC FOREIGN KEY (ID_TIP_DOC) REFERENCES TIPO_DOCUMENTO(ID_TIP_DOC)
);

CREATE TABLE VALORACION (
	VALR_ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255),
    PUNTUACION FLOAT(2) NOT NULL,
    FECHA_VALR DATE,
    EMPR_ID INT NOT NULL,
    USR_ID INT NOT NULL,
    CONSTRAINT FK_V_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID),
    CONSTRAINT FK_V_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT UNICA_VALR UNIQUE (USR_ID, EMPR_ID) #Para que el usuario no coloque 2 valoraciones en 1 misma empreas
);

CREATE TABLE DISCAPACIDAD (
	DISCAP_ID TINYINT PRIMARY KEY,
    NOMB_DISCAPACIDAD VARCHAR(50) UNIQUE
    
);

CREATE TABLE USUARIO_DISCAP (
	USR_ID INT NOT NULL,
    DISCAP_ID TINYINT NOT NULL,
    PRIMARY KEY (USR_ID, DISCAP_ID),
    CONSTRAINT fk_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT fk_DISCAP_ID FOREIGN KEY (DISCAP_ID) REFERENCES DISCAPACIDAD(DISCAP_ID)
);

CREATE TABLE NIVEL_EDUCATIVO (
	N_EDU_ID INT PRIMARY KEY,
    NOMB_NIV_EDU VARCHAR(255) UNIQUE
);

CREATE TABLE INSTITUCION (#
	INSTI_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    CIUDAD VARCHAR(255),
    DEPARTAMENTO VARCHAR(100),
    PAIS VARCHAR(100)
);

CREATE TABLE INFO_ESTUDIOS (#
	ESTUD_ID INT PRIMARY KEY,
    NOMB_ESTUDIO VARCHAR(255),
    FECHA_INI DATE,
    FECHA_FIN DATE,
    CERTIFICACION BLOB,
    N_EDU_ID INT NOT NULL,
    INSTI_ID INT NOT NULL,
    USR_ID INT NOT NULL,
    CONSTRAINT FK_N_EDU_ID FOREIGN KEY (N_EDU_ID) REFERENCES NIVEL_EDUCATIVO(N_EDU_ID),
    CONSTRAINT FK_INSTI_ID FOREIGN KEY (INSTI_ID) REFERENCES INSTITUCION(INSTI_ID),
    CONSTRAINT FK_E_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE INFO_EXPERIENCIA (#
	EXPE_ID INT PRIMARY KEY,
    CARGO VARCHAR(255),
    NOMB_EMPR VARCHAR(255),
    FECHA_INI DATE,
    FECHA_FIN DATE,
    DESCRIPCION VARCHAR(255),
    CIUDAD VARCHAR(255),
    PAIS VARCHAR(255),
    USR_ID INT NOT NULL,
    CONSTRAINT FK_X_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);

CREATE TABLE TIPO_CONTRATO (
	TIP_CONT_ID INT PRIMARY KEY,
    NOMB_CONTRATO VARCHAR(255)
);

CREATE TABLE MODALIDAD (
	MODAL_ID INT PRIMARY KEY,
    NOMB_MODALIDAD VARCHAR(255)
);

CREATE TABLE OFERTA (#
	OFER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMB_OFERTA VARCHAR (100),
    DESCRIPCION VARCHAR (255),
    UBIC_TRABAJO VARCHAR(100),
    FECHA_PUB DATE,
    FECHA_LIMIT DATE,
    MODAL_ID INT NOT NULL,
    TIP_CONT_ID INT NOT NULL,
    EMPR_ID INT NOT NULL,
    CONSTRAINT FK_MODAL_ID FOREIGN KEY (MODAL_ID) REFERENCES MODALIDAD(MODAL_ID),
    CONSTRAINT FK_TIP_CONT_ID FOREIGN KEY (TIP_CONT_ID) REFERENCES TIPO_CONTRATO(TIP_CONT_ID),
    CONSTRAINT FK_O_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID)
);

CREATE TABLE BENEFICIOS (
	BENEF_ID INT PRIMARY KEY,
    NOMB_BENEFICIO VARCHAR(255) UNIQUE
);

CREATE TABLE OFERTA_BENEFICIOS (#
	OFER_ID INT NOT NULL,
    BENEF_ID INT NOT NULL,
    PRIMARY KEY (OFER_ID, BENEF_ID),
    CONSTRAINT FK_BENEF_ID FOREIGN KEY (BENEF_ID) REFERENCES BENEFICIOS(BENEF_ID),
    CONSTRAINT FK_B_OFER_ID FOREIGN KEY (OFER_ID) REFERENCES OFERTA(OFER_ID)
);

CREATE TABLE ESTADOS (
	ESTAD_ID INT PRIMARY KEY,
    NOMB_ESTADO VARCHAR(10)
);

CREATE TABLE POSTULACIONES (#
	POSTUL_ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_POST DATE,
    ESTAD_ID INT NOT NULL,
    OFER_ID INT NOT NULL,
    USR_ID INT NOT NULL,
	CONSTRAINT FK_ESTAD_ID FOREIGN KEY (ESTAD_ID) REFERENCES ESTADOS(ESTAD_ID),
    CONSTRAINT FK_PO_OFER_ID FOREIGN KEY (OFER_ID) REFERENCES OFERTA(OFER_ID),
    CONSTRAINT FK_PO_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID)
);
