# INSERTAR EMPRESA

USE `workable`;
DROP procedure IF EXISTS `P_EMPRESA`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_EMPRESA` (
IN P_NOMB_EMPRESA VARCHAR(100),
IN P_DESCRIPCION_EMPR TEXT,
IN P_DIRECCION_EMPR VARCHAR(100),
IN P_CATEG_ID INT,
IN P_MUNI_ID INT
)
BEGIN
	INSERT INTO EMPRESA (NOMB_EMPRESA, DESCRIPCION_EMPR, DIRECCION_EMPR, CATEG_ID, MUNI_ID) 
    VALUES (P_NOMB_EMPRESA, P_DESCRIPCION_EMPR, P_DIRECCION_EMPR, P_CATEG_ID, P_MUNI_ID);
END$$

DELIMITER ;



# INSERTAR USUARIO

USE `workable`;
DROP procedure IF EXISTS `P_USUARIO`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_USUARIO` (
IN P_NOMBRE VARCHAR(50),
IN P_APELLIDO VARCHAR(50),
IN P_CLAVE VARCHAR(255),
IN P_DIRECCION VARCHAR(255),
IN P_CORREO VARCHAR(255),
IN P_USR_NAME VARCHAR(255),
IN P_TELEFONO INT,
IN P_FECHA_NACIMIENTO DATE,
IN P_FOTO_PERFIL BLOB,
IN P_GENR_ID BIT,
IN P_MUNI_ID INT,
IN P_EMPR_ID INT,
IN P_ROL_ID TINYINT,
IN P_ID_TIP_DOC INT
)

BEGIN
	DECLARE PWS VARCHAR(50) DEFAULT '12345';
    DECLARE CLAVE_ENC VARBINARY(500);
    SET CLAVE_ENC = AES_ENCRYPT(P_CLAVE, PWS);

	INSERT INTO USUARIO (NOMBRE, APELLIDO, CLAVE, DIRECCION, CORREO, USR_NAME, TELEFONO, FECHA_NACIMIENTO, FOTO_PERFIL, GENR_ID, MUNI_ID, EMPR_ID, ROL_ID, ID_TIP_DOC) 
    VALUES (P_NOMBRE, P_APELLIDO, CLAVE_ENC, P_DIRECCION, P_CORREO, P_USR_NAME, P_TELEFONO, P_FECHA_NACIMIENTO, P_FOTO_PERFIL, P_GENR_ID, P_MUNI_ID, P_EMPR_ID, P_ROL_ID, P_ID_TIP_DOC);
END$$

DELIMITER ;

# INSERTAR VALORACION

USE `workable`;
DROP procedure IF EXISTS `P_VALORACION`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_VALORACION` (
IN P_DESCRIPCION VARCHAR(255),
IN P_PUNTUACION FLOAT(2),
IN P_FECHA_VALR DATE,
IN P_EMPR_ID INT,
IN P_USR_ID INT
)

BEGIN
	IF P_PUNTUACION < 1 AND P_PUNTUACION >5 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT ='ERROR LA PUNTUACION DEBE SER ENTRE 1 Y 5';
    END IF;
    
	INSERT INTO VALORACION (DESCRIPCION, PUNTUACION, FECHA_VALR, EMPR_ID, USR_ID)
    VALUES (P_DESCRIPCION, P_PUNTUACION, CURDATE(), P_EMPR_ID, P_USR_ID);
END$$

DELIMITER ;

# DISCAPACIDAD DE USUARIO

USE `workable`;
DROP procedure IF EXISTS `P_SELECIONAR_DISCAP`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_SELECIONAR_DISCAP` (
IN P_USR_ID INT,
IN P_LISTA_DICAP_ID VARCHAR(255)
)

BEGIN
	DECLARE V_ID_DISCAP INT;
    DECLARE POSICION_COMA INT;
    DECLARE LISTA_REST VARCHAR(255);
    
	DELETE FROM USUARIO_DISCAP WHERE USR_ID = P_USR_ID;
    
    SET LISTA_REST = CONCAT(P_LISTA_DISCAP_ID, ',');
    
    WHILE LENGTH(LISTA_REST) > 0 DO
		SET POSICION_COMA = LOCATE(',', LISTA_REST);
        SET V_ID_DISCAP = CAST(TRIM(SUBSTRING(LISTA_REST, 1, POSICION_COMA -1)) AS UNSIGNED);
        
        IF V_ID_DISCAP > 0 THEN
			INSERT INTO USUARIO_DISCAP
            VALUES (P_USR_ID, V_ID_DISCAP);
		END IF;
        # no coloque else para condicionar que solo se elijan 1,2 y 3 porque en la plataforma debe ir la seleccion por checkbox
        SET LISTA_REST = SUBSTRING(LISTA_REST, POSICION_COMA + 1);
        
	END WHILE;
END$$

DELIMITER ;

# INFO PERSONAL

USE `workable`;
DROP procedure IF EXISTS `P_INFO_PERSONAL`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_INFO_PERSONAL` (
IN P_USR_ID INT,
IN P_DIRECCION VARCHAR(255),
IN P_TELEFONO INT,
IN P_FECHA_NACIMIENTO DATE,
IN P_FOTO_PERFIL BLOB,
IN P_GENR_ID BIT
)

BEGIN
	INSERT INTO INFO_PERSONAL 
    VALUES (P_USR_ID, P_DIRECCION, P_TELEFONO, P_FECHA_NACIMIENTO, P_FOTO_PERFIL, P_GENR_ID)
    ON DUPLICATE KEY UPDATE
		DIRECCION = P_DIRECCION, 
        TELEFONO = P_TELEFONO,
        FECHA_NACIMIENTO = P_FECHA_NACIMIENTO,
        FOTO_PERFIL = P_FOTO_PERFIL,
        GENR_ID = P_GENR_ID;
END$$

DELIMITER ;

# INSERTAR INSTITUCION