# INSERTAR EMPRESA
USE `workable`;
DROP procedure IF EXISTS `P_EMPRESA`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_EMPRESA` (
IN P_NOMBRE VARCHAR(100),
IN P_DESCRIPCION TEXT,
IN P_DIRECCION VARCHAR(100),
IN P_CATEG_ID INT,
IN P_MUNI_ID INT
)
BEGIN
	INSERT INTO EMPRESA (NOMBRE, DESCRIPCION, DIRECCION, CATEG_ID, MUNI_ID) 
    VALUES (P_NOMBRE, P_DESCRIPCION, P_DIRECCION, P_CATEG_ID, P_MUNI_ID);
END$$

DELIMITER ;




# INSERTAR USUARIO
USE `workable`;
DROP procedure IF EXISTS `P_USUARIO`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_USUARIO` (
IN P_NOMBRE VARCHAR(50),
IN P_APELLIDO VARCHAR(50),
IN P_CLAVE VARCHAR(255),
IN P_DIRECCION VARCHAR(255),
IN P_CORREO VARCHAR(255),
IN P_USR_NAME VARCHAR(255),
IN P_TELEFONO INT,
IN P_FECHA_NACIMIENTO DATE,
IN P_FOTO_PERFIL BLOB,
IN P_GENER_ID BIT,
IN P_MUNIC_ID INT,
IN P_EMPRE_ID INT,
IN P_ROL_ID TINYINT,
IN P_ID_TIP_DOC INT
)
BEGIN
	DECLARE PWS VARCHAR(50) DEFAULT '12345';
    DECLARE CLAVE_ENC VARBINARY(500);
    SET CLAVE_ENC = AES_ENCRYPT(P_CLAVE, PWS);

	INSERT INTO USUARIO (NOMBRE, APELLIDO, CLAVE, DIRECCION, CORREO, USR_NAME, TELEFONO, FECHA_NACIMIENTO, FOTO_PERFIL, GENER_ID, MUNIC_ID, EMPRE_ID, ROL_ID, ID_TIP_DOC) 
    VALUES (P_NOMBRE, P_APELLIDO, CLAVE_ENC, P_DIRECCION, P_CORREO, P_USR_NAME, P_TELEFONO, P_FECHA_NACIMIENTO, P_FOTO_PERFIL, P_GENER_ID, P_MUNIC_ID, P_EMPRE_ID, P_ROL_ID, P_ID_TIP_DOC);
END$$

DELIMITER ;




# INSERTAR VALORACION
USE `workable`;
DROP procedure IF EXISTS `P_VALORACION`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_VALORACION` (
IN P_DESCRIPCION VARCHAR(255),
IN P_PUNTUACION FLOAT(2),
IN P_EMPRE_ID INT,
IN P_USR_ID INT
)
BEGIN
	IF P_PUNTUACION < 1 AND P_PUNTUACION >5 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT ='ERROR LA PUNTUACION DEBE SER ENTRE 1 Y 5';
    END IF;
    
	INSERT INTO VALORACION (DESCRIPCION, PUNTUACION, VALR_FECHA, EMPRE_ID, USR_ID)
    VALUES (P_DESCRIPCION, P_PUNTUACION, CURDATE(), P_EMPRE_ID, P_USR_ID);
END$$

DELIMITER ;




# ELIMINAR E INSERTAR EN USUARIO_DISCAP
USE `workable`;
DROP procedure IF EXISTS `P_DISCAPACIDAD_ELM`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_DISCAPACIDAD_ELM` (
IN P_USR_ID INT
)
BEGIN
	DELETE FROM USUARIO_DISCAP WHERE USR_ID = P_USR_ID;
END$$

DELIMITER ;


USE `workable`;
DROP procedure IF EXISTS `P_DISCAPACIDAD`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_DISCAPACIDAD` (
IN P_USR_ID INT,
IN P_DISCAP_ID TINYINT
)
BEGIN
	INSERT IGNORE INTO USUARIO_DISCAP (USR_ID, DISCAP_ID)
	VALUES (P_USR_ID, P_DISCAP_ID);
END$$

DELIMITER ;




# INSERTAR ESTUDIOS
USE `workable`;
DROP procedure IF EXISTS `P_ESTUDIOS`;

DELIMITER $$
USE `workable`$$
CREATE PROCEDURE `P_ESTUDIOS` (
IN P_ESTUD_ID INT,
IN P_NOMBRE_PROGRAMA VARCHAR(255),
IN P_FECHA_INI DATE,
IN P_FECHA_FIN DATE,
IN P_CERTIFICADO_URL VARCHAR(512),
IN P_INSTI_ID INT,
IN P_USR_ID INT,
IN P_NIV_EDU_ID INT
)
BEGIN
	IF P_ESTUD_ID IS NULL OR P_ESTUD_ID = 0 THEN
		INSERT INTO ESTUDIO (NOMBRE_PROGRAMA, FECHA_INICIO, FECHA_FIN, CERTIFICADO_URL, INSTI_ID, USR_ID, NIV_EDU_ID)
        VALUES (P_NOMBRE_PROGRAMA, P_FECHA_INI, P_FECHA_FIN, P_CERTIFICADO_URL, P_INSTI_ID, P_USR_ID, P_NIV_EDU_ID);
    ELSE
		UPDATE ESTUDIO 
        SET NOMBRE_PROGRAMA = P_NOMBRE_PROGRAMA,
			FECHA_INICIO = P_FECHA_INICIO,
			FECHA_FIN = P_FECHA_FIN,
			CERTIFICADO_URL = P_CERTIFICADO_URL,
			INSTI_ID = P_INSTI_ID,
			NIV_EDU_ID = P_NIV_EDU_ID
        WHERE
			ESTUD_ID = P_ESTUD_ID AND USR_ID = P_USR_ID; -- se me olvido colocar que es para que un usuraio no pueda manipular la info de otro cambiando la id de solicitud
	END IF;
END$$

DELIMITER ;




# INSERTAR EXPERIENCIA
DROP PROCEDURE IF EXISTS `P_EXPERIENCIA`;
DELIMITER $$
CREATE PROCEDURE `P_EXPERIENCIA` (
    IN P_EXPE_ID INT,
    IN P_CARGO VARCHAR(255),
    IN P_NOMB_EMPRE VARCHAR(255),
    IN P_FECHA_INI DATE,
    IN P_FECHA_FIN DATE,
    IN P_DESCRIPCION TEXT,
    IN P_CIUDAD VARCHAR(255),
    IN P_PAIS VARCHAR(255),
    IN P_USR_ID INT
)
BEGIN
	IF P_EXPE_ID IS NULL OR P_EXPE_ID = 0 THEN
		INSERT INTO EXPERIENCIA (CARGO, NOMB_EMPRE, FECHA_INI, FECHA_FIN, DESCRIPCION, CIUDAD, PAIS, USR_ID) 
        VALUES (P_CARGO, P_NOMB_EMPRE, P_FECHA_INI, P_FECHA_FIN,P_DESCRIPCION, P_CIUDAD, P_PAIS, P_USR_ID);
    ELSE
        UPDATE EXPERIENCIA 
        SET CARGO = P_CARGO,
            NOMB_EMPRE = P_NOMB_EMPRE,
            FECHA_INI = P_FECHA_INI,
            FECHA_FIN = P_FECHA_FIN,
            DESCRIPCION = P_DESCRIPCION,
            CIUDAD = P_CIUDAD,
            PAIS = P_PAIS
        WHERE
            EXPE_ID = P_EXPE_ID AND USR_ID = P_USR_ID;
    END IF;
END$$

DELIMITER ;

# ELIMINAR EXPERIENCIA
DROP PROCEDURE IF EXISTS `P_EXPERIENCIA_ELM`;
DELIMITER $$
CREATE PROCEDURE `P_EXPERIENCIA_ELM` (
    IN P_EXPE_ID INT,
    IN P_USR_ID INT
)
BEGIN
    DELETE FROM EXPERIENCIA
    WHERE EXPE_ID = P_EXPE_ID AND USR_ID = P_USR_ID;
END$$

DELIMITER ;