USE `workable`;

DELIMITER $$

# VISTA DETALLE COMPLETO DE EMPRESAS CON UBICACION Y CATEGORIA
DROP VIEW IF EXISTS `V_EMPRESAS_DETALLE_GEOGRAFICO`;
$$
CREATE VIEW `V_EMPRESAS_DETALLE_GEOGRAFICO` AS
SELECT
  E.EMPRE_ID,
  E.NOMBRE AS NombreEmpresa,
  E.DESCRIPCION AS DescripcionEmpresa,
  E.DIRECCION AS DireccionEmpresa,
  CE.NOMBRE AS CategoriaEmpresa,
  CE.DESCRIPCION AS DescripcionCategoria,
  M.NOMBRE AS Municipio,
  D.NOMBRE AS Departamento,
  E.PUNTUACION_PROMEDIO
FROM
  EMPRESA AS E
JOIN
  CATEGORIA_EMPRE AS CE ON E.CATEG_ID = CE.CATEG_ID
JOIN
  MUNICIPIO AS M ON E.MUNIC_ID = M.MUNIC_ID
JOIN
  DEPARTAMENTO AS D ON M.DEPAR_ID = D.DEPAR_ID;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA DETALLE COMPLETO DE USUARIOS CON ROL Y UBICACION
DROP VIEW IF EXISTS `V_USUARIOS_PERFIL_COMPLETO`;
$$
CREATE VIEW `V_USUARIOS_PERFIL_COMPLETO` AS
SELECT
  U.USR_ID,
  U.NOMBRE AS NombreUsuario,
  U.APELLIDO AS ApellidoUsuario,
  U.CORREO AS CorreoUsuario,
  U.USR_NAME AS Username,
  U.TELEFONO,
  U.FECHA_NACIM,
  U.DIRECCION AS DireccionUsuario,
  U.FOTO_PERFIL,
  R.NOMBRE AS Rol,
  G.TIPO AS Genero,
  TD.NOMBRE AS TipoDocumento,
  M.NOMBRE AS Municipio,
  D.NOMBRE AS Departamento,
  E.NOMBRE AS NombreEmpresaAsociada
FROM
  USUARIO AS U
JOIN
  ROL AS R ON U.ROL_ID = R.ROL_ID
LEFT JOIN
  GENERO AS G ON U.GENER_ID = G.GENER_ID
JOIN
  MUNICIPIO AS M ON U.MUNIC_ID = M.MUNIC_ID
JOIN
  DEPARTAMENTO AS D ON M.DEPAR_ID = D.DEPAR_ID
JOIN
  TIPO_DOCUMENTO AS TD ON U.ID_TIP_DOC = TD.ID_TIP_DOC
LEFT JOIN
  EMPRESA AS E ON U.EMPRE_ID = E.EMPRE_ID;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA DETALLE COMPLETO DE OFERTAS DE EMPLEO
DROP VIEW IF EXISTS `V_OFERTAS_DETALLE_COMPLETO`;
$$
CREATE VIEW `V_OFERTAS_DETALLE_COMPLETO` AS
SELECT
  O.OFER_ID,
  O.NOMBRE AS TituloOferta,
  O.DESCRIPCION AS DescripcionOferta,
  O.DIRECCION AS DireccionOferta,
  O.FECHA_PUBLI,
  O.FECHA_LIMIT,
  E.NOMBRE AS NombreEmpresa,
  E.DIRECCION AS DireccionEmpresa,
  M.NOMBRE AS MunicipioOferta,
  D.NOMBRE AS DepartamentoOferta,
  MODL.NOMBRE AS Modalidad,
  TC.NOMBRE AS TipoContrato
FROM
  OFERTA AS O
JOIN
  EMPRESA AS E ON O.EMPRE_ID = E.EMPRE_ID
JOIN
  MUNICIPIO AS M ON O.MUNIC_ID = M.MUNIC_ID
JOIN
  DEPARTAMENTO AS D ON M.DEPAR_ID = D.DEPAR_ID
JOIN
  MODALIDAD AS MODL ON O.MODAL_ID = MODL.MODAL_ID
JOIN
  TIPO_CONTRATO AS TC ON O.TIP_CONT_ID = TC.TIP_CONT_ID;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA USUARIOS ASPIRANTES CON DISCAPACIDADES CONCATENADAS
DROP VIEW IF EXISTS `V_ASPIRANTES_CON_DISCAPACIDADES`;
$$
CREATE VIEW `V_ASPIRANTES_CON_DISCAPACIDADES` AS
SELECT
  U.USR_ID,
  U.NOMBRE AS NombreAspirante,
  U.APELLIDO AS ApellidoAspirante,
  U.CORREO AS CorreoAspirante,
  GROUP_CONCAT(D.NOMBRE ORDER BY D.NOMBRE SEPARATOR ', ') AS Discapacidades
FROM
  USUARIO AS U
JOIN
  USUARIO_DISCAP AS UD ON U.USR_ID = UD.USR_ID
JOIN
  DISCAPACIDAD AS D ON UD.DISCAP_ID = D.DISCAP_ID
WHERE
  U.ROL_ID = 2
GROUP BY
  U.USR_ID, U.NOMBRE, U.APELLIDO, U.CORREO;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA OFERTAS CON TODOS LOS BENEFICIOS CONCATENADOS
DROP VIEW IF EXISTS `V_OFERTAS_CON_TODOS_BENEFICIOS`;
$$
CREATE VIEW `V_OFERTAS_CON_TODOS_BENEFICIOS` AS
SELECT
  O.OFER_ID,
  O.NOMBRE AS TituloOferta,
  O.DESCRIPCION AS DescripcionOferta,
  O.FECHA_PUBLI,
  O.FECHA_LIMIT,
  GROUP_CONCAT(B.NOMBRE ORDER BY B.NOMBRE SEPARATOR ', ') AS BeneficiosOfrecidos
FROM
  OFERTA AS O
LEFT JOIN
  OFERTA_BENEFICIOS AS OB ON O.OFER_ID = OB.OFER_ID
LEFT JOIN
  BENEFICIOS AS B ON OB.BENEF_ID = B.BENEF_ID
GROUP BY
  O.OFER_ID, O.NOMBRE, O.DESCRIPCION, O.FECHA_PUBLI, O.FECHA_LIMIT;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA HISTORIAL COMPLETO DE POSTULACIONES
DROP VIEW IF EXISTS `V_POSTULACIONES_HISTORIAL_COMPLETO`;
$$
CREATE VIEW `V_POSTULACIONES_HISTORIAL_COMPLETO` AS
SELECT
  P.POSTUL_ID,
  P.FECHA_POST,
  S.NOMBRE AS EstadoPostulacion,
  U.USR_ID AS AspiranteID,
  U.NOMBRE AS NombreAspirante,
  U.APELLIDO AS ApellidoAspirante,
  U.CORREO AS CorreoAspirante,
  O.OFER_ID AS OfertaID,
  O.NOMBRE AS TituloOferta,
  E.EMPRE_ID AS EmpresaID,
  E.NOMBRE AS NombreEmpresa
FROM
  POSTULACIONES AS P
JOIN
  ESTADO AS S ON P.ESTAD_ID = S.ESTAD_ID
JOIN
  USUARIO AS U ON P.USR_ID = U.USR_ID
JOIN
  OFERTA AS O ON P.OFER_ID = O.OFER_ID
JOIN
  EMPRESA AS E ON O.EMPRE_ID = E.EMPRE_ID;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA USUARIOS RECLUTADORES AGRUPADOS POR EMPRESA
DROP VIEW IF EXISTS `V_RECLUTADORES_POR_EMPRESA`;
$$
CREATE VIEW `V_RECLUTADORES_POR_EMPRESA` AS
SELECT
  U.USR_ID,
  U.NOMBRE AS NombreReclutador,
  U.APELLIDO AS ApellidoReclutador,
  U.CORREO AS CorreoReclutador,
  E.EMPRE_ID,
  E.NOMBRE AS NombreEmpresa,
  E.DIRECCION AS DireccionEmpresa,
  M.NOMBRE AS MunicipioEmpresa,
  D.NOMBRE AS DepartamentoEmpresa
FROM
  USUARIO AS U
JOIN
  EMPRESA AS E ON U.EMPRE_ID = E.EMPRE_ID
JOIN
  MUNICIPIO AS M ON E.MUNIC_ID = M.MUNIC_ID
JOIN
  DEPARTAMENTO AS D ON M.DEPAR_ID = D.DEPAR_ID
WHERE
  U.ROL_ID = 3; -- ID para el rol 'Reclutador'
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA DETALLE COMPLETO DE ESTUDIOS DE USUARIOS
DROP VIEW IF EXISTS `V_ESTUDIOS_DETALLE_USUARIO`;
$$
CREATE VIEW `V_ESTUDIOS_DETALLE_USUARIO` AS
SELECT
  ES.ESTUD_ID,
  ES.NOMBRE_PROGRAMA,
  ES.FECHA_INI,
  ES.FECHA_FIN,
  ES.CERTIFICADO_URL,
  I.NOMBRE AS NombreInstitucion,
  NE.NOMBRE AS NivelEducativo,
  U.USR_ID,
  U.NOMBRE AS NombreUsuario,
  U.APELLIDO AS ApellidoUsuario
FROM
  ESTUDIO AS ES
JOIN
  USUARIO AS U ON ES.USR_ID = U.USR_ID
JOIN
  INSTITUCION AS I ON ES.INSTI_ID = I.INSTI_ID
JOIN
  NIVEL_EDUCATIVO AS NE ON ES.NIV_EDU_ID = NE.NIV_EDU_ID;
$$

DELIMITER ;

USE `workable`;

DELIMITER $$

# VISTA DETALLE COMPLETO DE EXPERIENCIAS LABORALES DE USUARIOS
DROP VIEW IF EXISTS `V_EXPERIENCIAS_DETALLE_USUARIO`;
$$
CREATE VIEW `V_EXPERIENCIAS_DETALLE_USUARIO` AS
SELECT
  EX.EXPE_ID,
  EX.CARGO,
  EX.NOMB_EMPRE,
  EX.FECHA_INI,
  EX.FECHA_FIN,
  EX.DESCRIPCION,
  EX.CIUDAD,
  EX.PAIS,
  U.USR_ID,
  U.NOMBRE AS NombreUsuario,
  U.APELLIDO AS ApellidoUsuario
FROM
  EXPERIENCIA AS EX
JOIN
  USUARIO AS U ON EX.USR_ID = U.USR_ID;
$$

DELIMITER ;