DROP DATABASE IF EXISTS WORKABLE;
CREATE DATABASE WORKABLE;
USE WORKABLE;

CREATE TABLE ROL (
	ROL_ID TINYINT PRIMARY KEY,
    NombreRol VARCHAR(10) UNIQUE
);

CREATE TABLE TIPO_DOCUMENTO (
	TIP_DOC_ID TINYINT PRIMARY KEY,
    DocNombre VARCHAR(20) 
);

CREATE TABLE DEPARTAMENTO (
	DEP_ID INT PRIMARY KEY,
    NombreDep VARCHAR (50)
);

CREATE TABLE CIUDAD (
	CIUD_ID INT PRIMARY KEY,
    NombreCiud VARCHAR(50) UNIQUE,
    DEP_ID INT NOT NULL,
    CONSTRAINT fk_DEP_ID FOREIGN KEY (DEP_ID) REFERENCES DEPARTAMENTO(DEP_ID)
);

CREATE TABLE CATEGORIA_EMPR (
	CATEG_ID INT PRIMARY KEY,
    NombreCatg VARCHAR(255) UNIQUE,
    IconImg BLOB,
    Descrip TEXT
);

CREATE TABLE EMPRESA (
	EMPR_ID INTEGER PRIMARY KEY,
    NombreEmpr VARCHAR(100) UNIQUE,
    UbicacionEmpr VARCHAR(255),
    DescripcionEmpr TEXT,
    CATEG_ID INT NOT NULL,
    CONSTRAINT fk_CATEG_ID FOREIGN KEY (CATEG_ID) REFERENCES CATEGORIA_EMPR(CATEG_ID)
);

CREATE TABLE USUARIO (
	USR_ID INT PRIMARY KEY,
    Nombre VARCHAR(100),
    Apellido VARCHAR(100),
    Clave VARCHAR(255),
    Correo VARCHAR(255) UNIQUE,
    UrsName VARCHAR(255) UNIQUE,
    CIUD_ID INT NOT NULL,
    EMPR_ID INT NOT NULL,
    TIP_DOC_ID TINYINT NOT NULL,
    ROL_ID TINYINT NOT NULL,
    CONSTRAINT fk_CIUD_ID FOREIGN KEY (CIUD_ID) REFERENCES CIUDAD(CIUD_ID),
    CONSTRAINT fk_EMPR_ID FOREIGN KEY (EMPR_ID) REFERENCES EMPRESA(EMPR_ID),
    CONSTRAINT fk_TIP_DOC_ID FOREIGN KEY (TIP_DOC_ID) REFERENCES TIPO_DOCUMENTO(TIP_DOC_ID),
    CONSTRAINT fk_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
);

CREATE TABLE DISCAPACIDAD (
	DISCAP_ID TINYINT PRIMARY KEY,
    NombreDiscap VARCHAR(50) UNIQUE
);

CREATE TABLE USUARIO_DISCAP (
	USR_ID INT NOT NULL,
    DISCAP_ID TINYINT NOT NULL,
    PRIMARY KEY (USR_ID, DISCAP_ID),
    CONSTRAINT fk_USR_ID FOREIGN KEY (USR_ID) REFERENCES USUARIO(USR_ID),
    CONSTRAINT fk_DISCAP_ID FOREIGN KEY (DISCAP_ID) REFERENCES DISCAPACIDAD(DISCAP_ID)
)
